<?php
/** @var \ExampleNew\ModuleOne\ViewModel\NewHomeOne $newHomeOne */
$newHomeOne = $block->getNewHomeOne();

/** @var \ExampleNew\ModuleTwo\ViewModel\NewHomeTwo $newHomeTwo */
$newHomeTwo = $block->getNewHomeTwo();

/** @var \ExampleNew\ModuleThree\ViewModel\NewHomeThree $newHomeThree */
$newHomeThree = $block->getNewHomeThree();
?>

<div>
    <p><?=$newHomeOne->getText()?> | <?=$newHomeTwo->getText()?> | <?=$newHomeThree->getText()?></p>
</div>